services:
- type: web
  name: student-management-system
  runtime: node
  buildCommand: cd client && npm install && npm run build
  startCommand: cd server && npm install && npm start
  envVars:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: 10000
  - key: MONGO_URI
    sync: false # This will prompt you to add the value in the Render dashboard
  staticPublishPath: client/build
